# fly.toml app configuration file generated for marketshare on 2023-09-14T20:23:55+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "marketshare"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]

[[mounts]]
  source = "marketshare"
  destination = "/mnt/marketshare"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
